server:
  port: 8080

spring:
  application:
    name: DevOpsDashboard
  
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/dashboarddb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE}
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
    driver-class-name: org.h2.Driver 
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL:}